spring.application.name=VisionCraft

server.port=${PORT:8080}



# =========================
# PostgreSQL / Supabase
# =========================
#
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# =========================
# JPA / Hibernate
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Hugging Face
# =========================

huggingface.api.url=https://router.huggingface.co/hf-inference/models/stabilityai/stable-diffusion-3-medium-diffusers
huggingface.api.token=${HF_API_TOKEN}

# =========================
# Image storage
# =========================

visioncraft.storage.path=generated-images

# =========================
# Logging
# =========================

logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =========================
# Supabase
# =========================

supabase.url=https://zozcbnljxuduotfkfqkp.supabase.co
supabase.storage.bucket=generated-images
supabase.service-key=${SUPABASE_SERVICE_KEY}
